-- ============================================================
-- Module 01: INVENTORY
-- Tables : products, inventory_logs
-- Used by: inventory.repository.js, billing.repository.js,
--          customer.repository.js (JOIN), report.repository.js
--
-- Source : Supabase information_schema export (column + constraint)
-- Run    : সবার আগে — বাকি প্রায় সব মডিউল products এর উপর নির্ভরশীল
-- ============================================================

-- ------------------------------------------------------------
-- products
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR NOT NULL,
    unit                    VARCHAR NOT NULL,
    buying_price            NUMERIC NOT NULL,
    default_selling_price   NUMERIC NOT NULL,
    current_stock           NUMERIC        DEFAULT 0,
    created_at              TIMESTAMPTZ    DEFAULT now(),
    unloading_labor_cost    NUMERIC,
    product_group           TEXT
);

-- getProducts() → ORDER BY name ASC
CREATE INDEX IF NOT EXISTS idx_products_name ON products (name);


-- ------------------------------------------------------------
-- inventory_logs
-- আনলোডিং লেবার খরচের লগ। report module এখান থেকেই দিনের
-- লেবার খরচ বের করে (getInventoryLogsByDate)।
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT REFERENCES products(id),
    product_name  TEXT,
    labor_cost    NUMERIC,
    created_at    TIMESTAMPTZ DEFAULT now()
);

-- getInventoryLogsByDate() → WHERE created_at BETWEEN ... ORDER BY created_at DESC
CREATE INDEX IF NOT EXISTS idx_inventory_logs_created_at ON inventory_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_inventory_logs_product_id ON inventory_logs (product_id);
