-- ============================================================
-- Module 02: CUSTOMERS
-- Tables : customers, customer_payments, advance_bookings,
--          product_returns, product_return_items, customer_ledger
-- Used by: customer.repository.js, billing.repository.js (ledger sync)
--
-- Source : Supabase information_schema export (column + constraint)
-- Run    : 001_inventory.sql এর পরে
--          (advance_bookings ও product_return_items → products FK)
-- ============================================================

-- ------------------------------------------------------------
-- customers
-- phone এ UNIQUE constraint আছে (Supabase এ confirm করা)।
-- Postgres এ একাধিক NULL phone allowed, তাই ফোন ছাড়া কাস্টমার
-- একাধিক থাকতে পারে — কোডও সেভাবেই লেখা (name দিয়ে খোঁজে)।
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    name               TEXT NOT NULL,
    phone              TEXT UNIQUE,
    total_due          NUMERIC NOT NULL DEFAULT 0,
    father_name        TEXT,
    customer_address   TEXT
);

-- getCustomers() → ORDER BY created_at DESC, আর name/phone দিয়ে ILIKE search
CREATE INDEX IF NOT EXISTS idx_customers_created_at ON customers (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customers_name       ON customers (name);


-- ------------------------------------------------------------
-- customer_payments
-- কলামের নাম payment_date (created_at না — customer.service.js এ
-- `p.payment_date || p.created_at` লেখা আছে, ওই fallback অংশটা
-- আসলে কখনো কাজে লাগে না)।
-- addPayment() payment_date পাঠায় না, তাই DEFAULT now() লাগবেই।
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT REFERENCES customers(id),
    amount_paid   NUMERIC NOT NULL,
    payment_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    note          TEXT
);

CREATE INDEX IF NOT EXISTS idx_customer_payments_customer_id ON customer_payments (customer_id);


-- ------------------------------------------------------------
-- advance_bookings
-- অগ্রিম বুকিং (locked price)। checkout এর সময় billing module
-- delivered_quantity বাড়ায় আর booked_quantity পূর্ণ হলে
-- status = 'completed' করে দেয়।
--
-- labor_advance কলামটা DB তে আছে কিন্তু backend এর কোথাও ব্যবহার
-- হয় না — সম্ভবত frontend থেকে বা future feature এর জন্য।
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS advance_bookings (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id           BIGINT  NOT NULL REFERENCES customers(id),
    product_id            INTEGER NOT NULL REFERENCES products(id),
    locked_price          NUMERIC NOT NULL,
    booked_quantity       NUMERIC NOT NULL,
    delivered_quantity    NUMERIC NOT NULL DEFAULT 0,
    status                TEXT    NOT NULL DEFAULT 'open',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    labor_advance         NUMERIC
);

-- getOpenBookingsForCustomerProduct() → customer_id + status ('open') + ORDER BY created_at
CREATE INDEX IF NOT EXISTS idx_advance_bookings_customer_status
    ON advance_bookings (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_advance_bookings_product_id
    ON advance_bookings (product_id);


-- ------------------------------------------------------------
-- product_returns  (মাল ফেরত — হেডার)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_returns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       BIGINT REFERENCES customers(id),
    customer_name     TEXT,
    customer_phone    TEXT,
    subtotal          NUMERIC NOT NULL,
    labor_cost        NUMERIC NOT NULL,
    labor_bearer      TEXT,
    transport_cost    NUMERIC NOT NULL,
    transport_bearer  TEXT,
    total_credited    NUMERIC NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_returns_customer_id ON product_returns (customer_id);


-- ------------------------------------------------------------
-- product_return_items  (মাল ফেরত — লাইন আইটেম)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_return_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id    BIGINT  REFERENCES product_returns(id),
    product_id   INTEGER REFERENCES products(id),
    quantity     NUMERIC NOT NULL,
    rate         NUMERIC NOT NULL,
    total_price  NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_product_return_items_return_id  ON product_return_items (return_id);
CREATE INDEX IF NOT EXISTS idx_product_return_items_product_id ON product_return_items (product_id);


-- ------------------------------------------------------------
-- customer_ledger
-- ⚠️ এই টেবিলটা Supabase এ আছে, কিন্তু backend এর একটা ফাইলেও
-- (repository / service / controller কোথাও) reference করা নেই —
-- পুরো src ফোল্ডার grep করে দেখা হয়েছে।
--
-- লক্ষণীয়: এর customer_id হলো INTEGER, অথচ customers.id হলো BIGINT।
-- এই টাইপ mismatch এর কারণেই সম্ভবত এটার উপর কোনো FK constraint নেই।
-- এটা ইঙ্গিত দেয় যে টেবিলটা আলাদাভাবে/আগে বানানো, বর্তমান স্কিমার
-- সাথে ঠিকভাবে যুক্ত না — অর্থাৎ সম্ভবত পুরনো (unused) টেবিল।
--
-- customer ledger এর আসল হিসাব এখন customer.service.js এর
-- generateLedgerData() রানটাইমে sales + payments + returns মিলিয়ে
-- বানায়, এই টেবিল থেকে পড়ে না।
--
-- production এর সাথে হুবহু মিল রাখার জন্য রাখা হলো। নিশ্চিত হয়ে
-- অপ্রয়োজনীয় মনে হলে এই ব্লকটা মুছে দিতে পারেন।
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_ledger (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      INTEGER,
    date             TIMESTAMPTZ,
    description      TEXT,
    debit            NUMERIC,
    credit           NUMERIC,
    running_balance  NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_customer_ledger_customer_id ON customer_ledger (customer_id);
