-- ============================================================
-- Module 03: SETTINGS
-- Tables : labor_settings
-- Used by: settings.repository.js (read + update),
--          inventory.repository.js (getLaborRate, insertLaborSetting),
--          billing.repository.js (getLaborSettings)
--
-- Source : Supabase information_schema export
-- Run    : কোনো টেবিলের উপর নির্ভরশীল না — যেকোনো সময় চালানো যায়
-- ============================================================

CREATE TABLE IF NOT EXISTS labor_settings (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_key              TEXT NOT NULL UNIQUE,
    category_name_bn          TEXT NOT NULL DEFAULT '',   -- ⚠️ নিচের নোট দেখুন
    rate_per_unit             NUMERIC NOT NULL,
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    unloading_rate_per_unit   NUMERIC
);

-- ⚠️ IMPORTANT — category_name_bn নিয়ে একটা সমস্যা ধরা পড়েছে:
--
-- Supabase এ এই কলামটা NOT NULL, কিন্তু inventory.repository.js এর
-- insertLaborSetting() ফাংশন শুধু (category_key, rate_per_unit,
-- unloading_rate_per_unit) ইনসার্ট করে — category_name_bn দেয় না।
--
-- মানে হয় production এ এই কলামের একটা DEFAULT সেট করা আছে, নাহলে
-- ওই ফাংশনটা আসলে fail করে (কেউ হয়তো এখনো ব্যবহার করেনি)।
-- এখানে DEFAULT '' বসিয়ে দিলাম যাতে local এ ফাংশনটা অন্তত crash না করে।
--
-- আসল default জানতে Supabase এ এটা চালাতে পারেন:
--   SELECT column_name, column_default FROM information_schema.columns
--   WHERE table_schema='public' AND table_name='labor_settings';
--
-- production এ যদি সত্যিই কোনো default না থাকে, তাহলে সবচেয়ে ভালো
-- হবে insertLaborSetting() এ category_name_bn টাও পাঠানো।


-- ------------------------------------------------------------
-- Seed data (optional)
-- inventory.service.js এর calculateUnloadingCost() এই ৫টা
-- category_key খোঁজে। row না থাকলে labor rate 0 ধরা হয়, তাই
-- local এ টেস্ট করার জন্য এগুলো বসিয়ে রাখা সুবিধাজনক।
-- রেট গুলো placeholder — নিজের আসল রেট বসিয়ে নেবেন।
-- ------------------------------------------------------------
INSERT INTO labor_settings (category_key, category_name_bn, rate_per_unit, unloading_rate_per_unit)
VALUES
    ('bag',    'ব্যাগ',   0, 0),
    ('kg',     'কেজি',    0, 0),
    ('bundle', 'বান্ডিল', 0, 0),
    ('pcs',    'পিস',     0, 0),
    ('others', 'অন্যান্য', 0, 0)
ON CONFLICT (category_key) DO NOTHING;
