-- ============================================================
-- Module 04: BILLING
-- Tables : sales, sale_items
-- Used by: billing.repository.js (checkoutRPC),
--          customer.repository.js (ledger), report.repository.js
--
-- Source : Supabase information_schema export (column + constraint)
-- Run    : 001_inventory.sql এর পরে (sale_items → products FK)
-- ============================================================

-- ------------------------------------------------------------
-- sales  (বিক্রির মেমো হেডার)
-- "previousDue" কলামটা camelCase — Postgres এ এরকম নাম সবসময়
-- ডাবল কোট দিয়ে লিখতে হয়। billing.repository.js এও কোট দিয়েই
-- লেখা আছে, তাই এখানেও হুবহু সেভাবেই রাখা হলো।
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    customer_name      TEXT NOT NULL,
    customer_phone     TEXT,
    subtotal           NUMERIC NOT NULL,
    labor_cost         NUMERIC,
    labor_bearer       TEXT,
    total_payable      NUMERIC NOT NULL,
    cash_paid          NUMERIC NOT NULL,
    due_amount         NUMERIC NOT NULL,
    customer_address   TEXT,
    father_name        TEXT,
    carrying_cost      NUMERIC,
    carrying_bearer    TEXT,
    "previousDue"      NUMERIC,
    discount_amount    NUMERIC
);

-- getSalesByCustomer() → phone অথবা name দিয়ে খোঁজে
CREATE INDEX IF NOT EXISTS idx_sales_customer_phone ON sales (customer_phone);
CREATE INDEX IF NOT EXISTS idx_sales_customer_name  ON sales (customer_name);
-- getSalesByDate() → WHERE created_at BETWEEN ... ORDER BY created_at DESC
CREATE INDEX IF NOT EXISTS idx_sales_created_at     ON sales (created_at DESC);


-- ------------------------------------------------------------
-- sale_items  (মেমোর লাইন আইটেম)
--
-- ⚠️ লক্ষণীয় — sale_id এর উপর production এ কোনো FOREIGN KEY নেই,
-- যদিও এটা আসলে sales.id কেই point করে। কারণটা টাইপ mismatch:
-- sales.id হলো BIGINT, কিন্তু sale_items.sale_id হলো INTEGER।
-- (customer.repository.js এও ANY($1::int[]) cast করা আছে, অর্থাৎ
-- কোডও integer ধরেই চলছে।)
--
-- production এর সাথে হুবহু মিল রাখতে FK ছাড়াই রাখা হলো। ভবিষ্যতে
-- ঠিক করতে চাইলে দুটোকেই BIGINT করে তারপর FK যোগ করতে হবে —
-- সেটা একটা আলাদা migration হিসেবে করবেন, এই ফাইল এডিট করে না।
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sale_items (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id          INTEGER,
    product_id       INTEGER REFERENCES products(id),
    quantity         NUMERIC NOT NULL,
    price_per_unit   NUMERIC NOT NULL,
    total_price      NUMERIC NOT NULL
);

-- getSaleItemsBySaleIds() → WHERE sale_id = ANY(...)
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id    ON sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON sale_items (product_id);
