-- ============================================================
-- Module 02 (addendum): CUSTOMER PHONES
-- Tables : customer_phones
-- ============================================================
-- একজন কাস্টমারের একাধিক ফোন নাম্বার রাখার জন্য। customers.phone
-- কলামটা মুছে ফেলা হয়নি — সেটাই থাকবে "প্রধান/display নাম্বার"
-- (মেমো, লিস্টে যেটা দেখায়)। এই নতুন টেবিলে প্রধান নাম্বারসহ
-- কাস্টমারের সব নাম্বার থাকবে, প্রতিটা globally UNIQUE — একই
-- নাম্বার দুই কাস্টমারের নামে বসতে পারবে না।
--
-- Depends on: 002_customers.sql (customers টেবিল আগে থাকতে হবে)
-- Run: 002_customers.sql এর পরে যেকোনো সময়
-- ============================================================

CREATE TABLE IF NOT EXISTS customer_phones (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    phone         TEXT NOT NULL UNIQUE,
    is_primary    BOOLEAN NOT NULL DEFAULT false,
    label         TEXT,              -- "নিজের", "ছেলের", "অফিস" ইত্যাদি, ঐচ্ছিক
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_customer_phones_customer_id ON customer_phones (customer_id);

-- ------------------------------------------------------------
-- ব্যাকফিল — existing customers.phone গুলো এখানে "প্রধান নাম্বার"
-- হিসেবে কপি করা হলো, যাতে ফোন খোঁজার সব লজিক এখন থেকে শুধু এই
-- একটা টেবিল দেখলেই চলে (customers.phone সরাসরি না ছুঁয়ে)।
-- ON CONFLICT DO NOTHING — যদি migration দুইবার চলে, বা কোনো
-- কারণে phone আগে থেকেই থাকে, error না দিয়ে skip করবে।
-- ------------------------------------------------------------
INSERT INTO customer_phones (customer_id, phone, is_primary)
SELECT id, phone, true
FROM customers
WHERE phone IS NOT NULL AND phone <> ''
ON CONFLICT (phone) DO NOTHING;
